"""init tables

Revision ID: dd18a7d08873
Revises: 
Create Date: 2026-01-25 13:42:36.924543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd18a7d08873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_vehicles_brand'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_model'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_cart_items_part_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.add_column('part', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('part', sa.Column('condition', sa.String(length=10), nullable=False))
    op.add_column('part', sa.Column('originality', sa.String(length=10), nullable=False))
    op.add_column('part', sa.Column('cross_brand', sa.Integer(), nullable=False))
    op.alter_column('part', 'category',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('part', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('part', 'brand',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('part', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_parts_brand'), table_name='part')
    op.drop_index(op.f('ix_parts_category'), table_name='part')
    op.drop_index(op.f('ix_parts_sku'), table_name='part')
    op.drop_column('part', 'in_stock')
    op.drop_column('part', 'sku')
    op.drop_column('part', 'name')
    op.drop_column('part', 'description')
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'name')
    op.add_column('part', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('part', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('part', sa.Column('sku', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('part', sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_parts_sku'), 'part', ['sku'], unique=True)
    op.create_index(op.f('ix_parts_category'), 'part', ['category'], unique=False)
    op.create_index(op.f('ix_parts_brand'), 'part', ['brand'], unique=False)
    op.alter_column('part', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('part', 'brand',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('part', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('part', 'category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('part', 'cross_brand')
    op.drop_column('part', 'originality')
    op.drop_column('part', 'condition')
    op.drop_column('part', 'title')
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], name=op.f('cart_items_part_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cart_items_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey'))
    )
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_cart_items_part_id'), 'cart_items', ['part_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('year_from', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_to', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('drive', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('transmission', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey'))
    )
    op.create_index(op.f('ix_vehicles_model'), 'vehicles', ['model'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_brand'), 'vehicles', ['brand'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('orders_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###
